### ISSUE TITLE
Update module to the newest system version?

### ISSUE THREAD

**Issue by robert16444** [thatlonelybugbear/automated-conditions-5e#155] opened 2024-09-28 16:02 UTC
Current D&D5e version is 4.0.4. This module won't work on any version equal or higher to 4.0.0. 
Will it be updated?

**Comment by thatlonelybugbear** [comment] 2024-09-28 16:09
Yes as soon as I have time to tackle the changes needed.

**Comment by thatlonelybugbear** [comment] 2024-11-07 14:15
Closing this as duplicate of #172 

Will update soon.

**Closed by thatlonelybugbear** 2024-11-07 14:15 UTC
Labels: duplicate, working on
